String termsText =
<<<<<<< HEAD
    'THESE ARE THE TERMS FOR USING TRADEGROUNDS. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Hendrerit dolor magna eget est lorem ipsum dolor sit. Pretium lectus quam id leo in vitae turpis massa sed. Ultricies integer quis auctor elit sed vulputate mi sit. Lectus magna fringilla urna porttitor rhoncus. Feugiat nisl pretium fusce id velit ut. Elit eget gravida cum sociis natoque penatibus et magnis. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. At volutpat diam ut venenatis tellus in metus vulputate. Turpis tincidunt id aliquet risus feugiat in. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Enim ut tellus elementum sagittis vitae et leo duis ut. Feugiat vivamus at augue eget arcu dictum varius duis at. Mi in nulla posuere sollicitudin. Vel eros donec ac odio tempor. Amet facilisis magna etiam tempor orci eu lobortis elementum. Id faucibus nisl tincidunt eget nullam non nisi est. Amet est placerat in egestas erat imperdiet. Ut etiam sit amet nisl purus in mollis nunc.Nec feugiat in fermentum posuere urna nec tincidunt praesent. Egestas dui id ornare arcu odio ut sem. Morbi tristique senectus et netus. Arcu ac tortor dignissim convallis aenean et tortor at. Eros donec ac odio tempor orci dapibus ultrices. Neque vitae tempus quam pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Non nisi est sit amet facilisis. Urna porttitor rhoncus dolor purus non enim praesent elementum. Viverra vitae congue eu consequat. Sit amet consectetur adipiscing elit duis tristique. Egestas erat imperdiet sed euismod nisi porta. Volutpat est velit egestas dui. Integer eget aliquet nibh praesent tristique. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Semper eget duis at tellus at. Venenatis cras sed felis eget velit aliquet sagittis id. Sed arcu non odio euismod lacinia.Tortor dignissim convallis aenean et tortor at. Non diam phasellus vestibulum lorem sed risus. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Vitae congue eu consequat ac felis donec et.';

var termsObject = {
  "title": "Tradegrounds Terms of Use",
  "lastUpdated": "Last Updated March 3 2021",
  "body":
      "THESE ARE THE TERMS FOR USING TRADEGROUNDS. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Hendrerit dolor magna eget est lorem ipsum dolor sit. Pretium lectus quam id leo in vitae turpis massa sed. Ultricies integer quis auctor elit sed vulputate mi sit. Lectus magna fringilla urna porttitor rhoncus. Feugiat nisl pretium fusce id velit ut. Elit eget gravida cum sociis natoque penatibus et magnis. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. At volutpat diam ut venenatis tellus in metus vulputate. Turpis tincidunt id aliquet risus feugiat in. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Enim ut tellus elementum sagittis vitae et leo duis ut. Feugiat vivamus at augue eget arcu dictum varius duis at. Mi in nulla posuere sollicitudin. Vel eros donec ac odio tempor. Amet facilisis magna etiam tempor orci eu lobortis elementum. Id faucibus nisl tincidunt eget nullam non nisi est. Amet est placerat in egestas erat imperdiet. Ut etiam sit amet nisl purus in mollis nunc.Nec feugiat in fermentum posuere urna nec tincidunt praesent. Egestas dui id ornare arcu odio ut sem. Morbi tristique senectus et netus. Arcu ac tortor dignissim convallis aenean et tortor at. Eros donec ac odio tempor orci dapibus ultrices. Neque vitae tempus quam pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Non nisi est sit amet facilisis. Urna porttitor rhoncus dolor purus non enim praesent elementum. Viverra vitae congue eu consequat. Sit amet consectetur adipiscing elit duis tristique. Egestas erat imperdiet sed euismod nisi porta. Volutpat est velit egestas dui. Integer eget aliquet nibh praesent tristique. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Semper eget duis at tellus at. Venenatis cras sed felis eget velit aliquet sagittis id. Sed arcu non odio euismod lacinia.Tortor dignissim convallis aenean et tortor at. Non diam phasellus vestibulum lorem sed risus. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Vitae congue eu consequat ac felis donec et."
};
=======
    'THESE ARE THE TERMS FOR USING TRADEGROUNDS. This is to make the merge happen. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Hendrerit dolor magna eget est lorem ipsum dolor sit. Pretium lectus quam id leo in vitae turpis massa sed. Ultricies integer quis auctor elit sed vulputate mi sit. Lectus magna fringilla urna porttitor rhoncus. Feugiat nisl pretium fusce id velit ut. Elit eget gravida cum sociis natoque penatibus et magnis. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. At volutpat diam ut venenatis tellus in metus vulputate. Turpis tincidunt id aliquet risus feugiat in. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Enim ut tellus elementum sagittis vitae et leo duis ut. Feugiat vivamus at augue eget arcu dictum varius duis at. Mi in nulla posuere sollicitudin. Vel eros donec ac odio tempor. Amet facilisis magna etiam tempor orci eu lobortis elementum. Id faucibus nisl tincidunt eget nullam non nisi est. Amet est placerat in egestas erat imperdiet. Ut etiam sit amet nisl purus in mollis nunc.Nec feugiat in fermentum posuere urna nec tincidunt praesent. Egestas dui id ornare arcu odio ut sem. Morbi tristique senectus et netus. Arcu ac tortor dignissim convallis aenean et tortor at. Eros donec ac odio tempor orci dapibus ultrices. Neque vitae tempus quam pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Non nisi est sit amet facilisis. Urna porttitor rhoncus dolor purus non enim praesent elementum. Viverra vitae congue eu consequat. Sit amet consectetur adipiscing elit duis tristique. Egestas erat imperdiet sed euismod nisi porta. Volutpat est velit egestas dui. Integer eget aliquet nibh praesent tristique. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Semper eget duis at tellus at. Venenatis cras sed felis eget velit aliquet sagittis id. Sed arcu non odio euismod lacinia.Tortor dignissim convallis aenean et tortor at. Non diam phasellus vestibulum lorem sed risus. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Vitae congue eu consequat ac felis donec et.';
>>>>>>> e6cc1c71ccfe732e6ead804b06d5d854c4317106
